In this notebook I'm going to prove the assumptions made in the section `1.12` from the PROJECT_WALTHROUGH.md file

## 1.12 Verify assumptions if possible

First of all I assume that the dataset contains all relevant features required to model the target variable, and that no critical predictive information is systematically missing.

Since this is the first version of the project those will be the project I will only verify the following assumptions:

| Assumption | Verification Method | 
|------------|---------------------|
| Data completeness | Number of columns and rows match the document | 
| Time coverage | The dataset represents data from the whole year 2024 |
| Class imbalance | Verify that the imbalance is 25% | Verified: 25% cancellation rate |
| Valid target | Target column exists and it's in the format that the business needs to predict | 
| No obvious data leakage | Post-cancellation columns are removed |

In [18]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [19]:
df = pd.read_csv("../data/raw/ncr_ride_bookings.csv")
df.head(20)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,NaN,NaN,NaN,NaN,NaN,NaN,316.0,4.85,4.1,4.6,UPI
6,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,NaN,NaN,NaN,NaN,NaN,NaN,640.0,41.24,4.0,4.1,UPI
7,2024-03-19,17:37:37,"""CNR6568000""",Completed,"""CID8610436""",Auto,Mayur Vihar,Cyber Hub,12.1,16.5,NaN,NaN,NaN,NaN,NaN,NaN,136.0,6.56,4.4,4.2,UPI
8,2024-09-14,12:49:09,"""CNR4510807""",No Driver Found,"""CID7873618""",Go Sedan,Noida Sector 62,Noida Sector 18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-12-16,19:06:48,"""CNR7721892""",Incomplete,"""CID5214275""",Auto,Rohini,Adarsh Nagar,6.1,26.0,NaN,NaN,NaN,NaN,1.0,Other Issue,135.0,10.36,NaN,NaN,Cash
10,2024-06-14,16:24:12,"""CNR9070334""",Completed,"""CID6680340""",Auto,Udyog Bhawan,Dwarka Sector 21,7.7,18.9,NaN,NaN,NaN,NaN,NaN,NaN,181.0,19.84,4.2,4.9,Cash
11,2024-09-18,08:09:38,"""CNR9551927""",No Driver Found,"""CID7568143""",Auto,Vidhan Sabha,AIIMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024-06-25,22:44:15,"""CNR4386945""",Cancelled by Driver,"""CID5543520""",eBike,Patel Chowk,Kherki Daula Toll,4.6,NaN,NaN,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2024-09-11,19:29:39,"""CNR2987763""",Completed,"""CID2669710""",Go Mini,Malviya Nagar,Ghitorni Village,12.2,28.2,NaN,NaN,NaN,NaN,NaN,NaN,394.0,21.44,4.1,4.7,UPI
14,2024-10-18,18:28:53,"""CNR8962232""",Completed,"""CID1789354""",Go Mini,Madipur,GTB Nagar,14.0,30.9,NaN,NaN,NaN,NaN,NaN,NaN,836.0,39.55,4.7,4.4,UPI
15,2024-06-07,15:05:35,"""CNR2390352""",Completed,"""CID5432215""",Auto,Jama Masjid,Khan Market,8.5,36.9,NaN,NaN,NaN,NaN,NaN,NaN,410.0,34.76,4.0,4.9,Uber Wallet
16,2024-07-01,10:51:16,"""CNR3221338""",Completed,"""CID2581698""",Premier Sedan,IGI Airport,Madipur,5.6,27.5,NaN,NaN,NaN,NaN,NaN,NaN,401.0,21.97,4.9,4.3,UPI
17,2024-12-15,15:08:25,"""CNR6739317""",Cancelled by Driver,"""CID8682675""",Go Sedan,Vinobapuri,GTB Nagar,6.0,NaN,NaN,NaN,1.0,Customer related issue,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2024-11-24,09:07:10,"""CNR6126048""",Cancelled by Customer,"""CID1060329""",eBike,Kashmere Gate,Anand Vihar,12.4,NaN,1.0,Driver is not moving towards pickup location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2024-05-24,19:53:57,"""CNR9465840""",Cancelled by Driver,"""CID9046501""",eBike,Pitampura,Rajiv Nagar,10.3,NaN,NaN,NaN,1.0,Customer related issue,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data completeness

Do the columns and rows of the dataset match the document?

In [20]:
df.info(verbose= True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

- Columns: 150000
- Rows = 21
  
There is a mismatch between the document's information and the dataset. Let's check if there are duplicated rows based on Customer ID

In [21]:
df["Customer ID"].nunique()

148788

The document appears outdated or contains an error, as unique users seem to have been mixed with total rows. Let's see if I can find something outstanding at first sight in those duplicated rows

In [22]:
df[df["Customer ID"].duplicated(keep = False)].sort_values(by = "Customer ID").head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
87396,2024-03-28,09:04:44,"""CNR6195473""",Cancelled by Driver,"""CID1008198""",Premier Sedan,Aya Nagar,Ghaziabad,8.5,NaN,NaN,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74564,2024-03-18,20:44:08,"""CNR9208385""",Completed,"""CID1008198""",Auto,Noida Sector 62,Karkarduma,12.8,25.6,NaN,NaN,NaN,NaN,NaN,NaN,572.0,25.24,4.3,4.3,UPI
129004,2024-03-02,17:37:00,"""CNR9673455""",Completed,"""CID1008784""",Premier Sedan,RK Puram,Subhash Nagar,3.7,29.2,NaN,NaN,NaN,NaN,NaN,NaN,217.0,49.32,4.2,4.3,Uber Wallet
92529,2024-06-03,15:56:24,"""CNR4575076""",Completed,"""CID1008784""",Bike,RK Puram,Green Park,9.0,33.1,NaN,NaN,NaN,NaN,NaN,NaN,90.0,32.75,3.2,4.2,Uber Wallet
22845,2024-12-19,15:01:41,"""CNR7339507""",Completed,"""CID1031312""",Uber XL,Aya Nagar,Pragati Maidan,10.5,41.5,NaN,NaN,NaN,NaN,NaN,NaN,341.0,34.45,3.7,4.4,Cash

At first glance, duplicated rows just represent different bookings from the same customer, not errors in the system. Anyways for the scope of this project I will leave it here but it would be necessary to perform a further investigation of these rows to double check the assumption I just made.

## Time coverage

Is the dataset really covering the whole year 2024?

In [23]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
full_range = pd.date_range(start='2024-01-01', end='2024-12-31', freq='D')
daily_counts = df.groupby('Date').size()
missing_days = full_range.difference(daily_counts.index)
print("Days without data:", missing_days)
print("Number of missing days:", len(missing_days))

Days without data: DatetimeIndex(['2024-12-31'], dtype='datetime64[ns]', freq='D')
Number of missing days: 1

The dataset includes all days of the year except December 31st. It is important to note this omission and, if possible, obtain the data for December 31st to ensure the model covers the full year

# Class Imbalance

Does the dataset really contain a 25% of cancellations?

In [24]:
df["Booking Status"].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [25]:
cancellations_count = df["Booking Status"].isin(["Cancelled by Driver", "Cancelled by Customer"]).sum()
print(f"Cancellation rate is: {round((cancellations_count/ len(df))* 100) }%")
print(f"Cancellation count: {cancellations_count}")

Cancellation rate is: 25%
Cancellation count: 37500

The dataset contains a 25% of cancellations

# Valid target

In this project I have to predict the cancellation of a ride, this means that the target should be binary.

The old and new labels for the column "Booking Status" are the following:

| Old Label | Classified as | New Label |
|-----------------|-----------|---------|
| Completed |               not cancelled | 0
| Cancelled by Driver |     cancelled | 1 
| No Driver Found |         not cancelled | 0
| Cancelled by Customer |   cancelled | 1
| Incomplete |              not cancelled | 0

This step is done in the notebook `03_initial_data_inspection.ipynb`

# Data leakage

Are there columns that refer to the future?

In [26]:
df.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='object')

Columns that are clearly not leaking:
- Date
- Time
- Booking ID
- Booking status 
- Customer ID 
- Vehicle Type 
- Pickup Location
- Drop locations
- avg VTAT
- avg CTAT 
- Booking Value
- Ride Distance
- Payment Method


Leaking columns: 
- Cancelled Rides by Driver (flag)
- Cancelled Rides by Customer (flag)
- Reason for cancelling by Customer (future)
- Driver Cancellation Reason (future)
- Incomplete Rides (flag)
- Incomplete Rides Reason (future)
- Driver Ratings (future)
- Customer Rating (future)